import "./globals.css";
import "../components/styles/carrossel.css";
import "../components/styles/nutricional.module.css";

import Carrossel from '../components/banner/banner';
//import { Header } from '../components/header'
import Footer  from '../components/footer/footer'  


import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../components/styles/styles.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900"
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'antialiased'}>
        <Carrossel/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}

